/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AncientEnvelope: typeof import('./src/components/AncientEnvelope/AncientEnvelope.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
    LetterComponent: typeof import('./src/components/LetterComponent/LetterComponent.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LyricsScrolling: typeof import('./src/components/LyricsScrolling/LyricsScrolling.vue')['default']
    MagicLetter: typeof import('./src/components/MagicLetter/MagicLetter.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MoreContent: typeof import('./src/components/MoreContent.vue')['default']
    Music: typeof import('./src/components/Music.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Set: typeof import('./src/components/Set.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    TextDisplay: typeof import('./src/components/TextDisplay.vue')['default']
    TimeCapsule: typeof import('./src/components/TimeCapsule.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanImage: typeof import('vant/es')['Image']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    Weather: typeof import('./src/components/Weather.vue')['default']
  }
}
