# Dev 分支推送部署到Linux服务器
name: Deploy to Server from Dev branch Home

on:
  push:
    branches:
      - dev
      - master

jobs:
  build-and-deploy:
    name: Build and deploy to server
    runs-on: ubuntu-latest

    steps:
    - name: Check out git repository
      uses: actions/checkout@v4.1.1

    - name: Install Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: "18.x"

    - name: Copy .env.example
      run: |
        if [ ! -f .env ]; then
          cp .env.example .env
        else
          echo ".env file already exists. Skipping the copy step."
        fi

    - name: Install Dependencies
      run: npm install

    - name: Build Website
      run: npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - uses: actions/checkout@v4
    - name: Deploy to Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SITKIN }}
        port: ${{ secrets.PORT }}
        source: "dist/*"
        target: "/opt/1panel/apps/openresty/openresty/www/sites/home.sitkin.top/index"
